on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Testing with Laravel ${{ matrix.laravel }} and PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: [7.4, 8.0]
        laravel: [^7.0, ^8.0, ^9.0]
        exclude:
          - laravel: ^9.0
            php: 7.4
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer require "illuminate/bus:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "illuminate/queue:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-ansi --no-progress

      - name: Execute tests
        run: |
          vendor/bin/phpcs
          vendor/bin/phpunit
